export const iconList = [
  ["Feather", "mail"],
  ["Feather", "lock"],
  ["Feather", "user"],
  ["Feather", "smartphone"],
  ["Entypo", "eye"],
  ["Entypo", "eye-with-line"],
  ["Ionicons", "chevron-back-sharp"],
  ["Ionicons", "home"],
  ["FontAwesome5", "home"],
  ["FontAwesome5", "map-marker-alt"],
  ["FontAwesome5", "calendar-alt"],
  ["FontAwesome5", "question-circle"],
  ["FontAwesome5", "user-circle"],
  ["FontAwesome5", "user-alt"],
  ["FontAwesome5", "table"],
  ["FontAwesome5", "history"],
  ["FontAwesome5", "cog"],
  ["FontAwesome5", "sign-in-alt"],
  ["FontAwesome5", "sign-out-alt"],
];
